# Generated by Django 3.0 on 2019-12-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsRecipients',
            new_name='NewsLetterRecipients',
        ),
    ]
