# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191211_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=(), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
